repos:
- repo: local
  hooks:
    - id: clippy
      name: clippy
      description: Lint rust sources
      entry: cargo clippy
      language: system
      args: ["--", "-W", "warnings"]
      types: [rust]
      pass_filenames: false
