name: Crypto Social DB CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'crates/crypto_social_db/**'
  pull_request:
    branches: [main]
    paths:
      - 'crates/crypto_social_db/**'

env:
  CARGO_TERM_COLOR: always
  AWS_REGION: us-east-1  # Replace with your AWS region
  ECR_REPOSITORY: crypto-social-db  # Replace with your ECR repository name

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --manifest-path crates/crypto_social_db/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path crates/crypto_social_db/Cargo.toml

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2

    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ${{ env.AWS_REGION }}

    # - name: Login to Amazon ECR
    #   id: login-ecr
    #   uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: "teste"
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f crates/crypto_social_db/Dockerfile .

